---
# minio will be denied, as it has no signature and it is not in the exempted images
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: minio
  name: minio
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
    spec:
      containers:
      - image: bitnami/minio
        name: minio
        resources: {}
---
# ghcr.io/falcorocks/learns should be admitted as it has a valid signature produced by the expected identity (github token)
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: falcorocks-nginx
  name: falcorocks-nginx
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcorocks-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: falcorocks-nginx
    spec:
      containers:
      - image: ghcr.io/falcorocks/learns@sha256:4ac65f23061de2faef157760fa2125c954b5b064bc25e10655e90bd92bc3b354
        name: learns
        resources: {}
status: {}
---
# nginx should be admitted as it is part of the exemptedImages

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}