name: keyed cosign @ttl.sh + PROMOTION

on:
  push:
    branches: ['main']

env:
  IMAGE: ttl.sh/keyed-${{github.sha}}:1h

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/prepare
    - name: build
      run: cosign copy alpine $IMAGE
    - name: dev test
      run: sleep 1
    - name: promote image to staging
      run: cosign sign --yes --key cosign.key ${CLAIMS} -a porcelain=$PORCELAIN -a promotion=staging $IMAGE@$DIGEST
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    - run: crane manifest $(cosign triangulate $IMAGE) | jq .
  staging:
    runs-on: ubuntu-latest
    needs: dev
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/prepare
    - name: verify image & claims
      run: cosign verify --key cosign.pub ${CLAIMS} -a porcelain=0 -a promotion=staging $IMAGE@$DIGEST
    - name: staging test
      run: sleep 1
    - name: promote image to production
      run: cosign sign --yes --key prod.key ${CLAIMS} -a promotion=production $IMAGE@$DIGEST
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD_PROD }}
    - run: crane manifest $(cosign triangulate $IMAGE) | jq .
  production:
    needs: staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/prepare
    - name: verify image & claims
      run: cosign verify --key prod.pub ${CLAIMS} -a porcelain=0 -a promotion=production $IMAGE@$DIGEST
