name: keyless cosign @ttl.sh

on:
  push:
    branches: ['main']

env:
  IMAGE: ttl.sh/keyless-${{github.sha}}:1h

jobs:
  cosign-keyless:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: sigstore/cosign-installer@main
      with:
        cosign-release: "v2.1.1"
    - run: cosign copy alpine $IMAGE
    - uses: imjasonh/setup-crane@v0.1
    - run: DIGEST=$(crane digest $IMAGE) && cosign sign --yes $IMAGE@$DIGEST
    - run: crane manifest $(cosign triangulate $IMAGE) | jq .
    - name: verify
      run: DIGEST=$(crane digest $IMAGE) && cosign verify $IMAGE@$DIGEST --certificate-identity=https://github.com/falcorocks/learns/.github/workflows/cosign-keyless-ttl.yml@refs/heads/main --certificate-oidc-issuer=https://token.actions.githubusercontent.com
