name: cosign ghcr.io

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main']

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_URL: ghcr.io/${{ github.repository }}:${{github.sha}}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  cosign-keyless:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v2.1.1" # optional
      - name: prepare image
        run: cosign copy alpine ${{ env.IMAGE_URL }}
      - uses: imjasonh/setup-crane@v0.1
      - name: cosign-keyless
        run: DIGEST=$(crane digest  ${{ env.IMAGE_URL }}) && cosign sign --yes  ${{ env.IMAGE_URL }}@$DIGEST