name: keyed cosign @ttl.sh

on:
  push:
    branches: ['main']

env:
  IMAGE: ttl.sh/keyed-${{github.sha}}:1h

jobs:
  cosign-keyed:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: sigstore/cosign-installer@main
      with:
        cosign-release: "v2.1.1"
    - run: cosign copy alpine $IMAGE
    - uses: imjasonh/setup-crane@v0.1
    - run: DIGEST=$(crane digest $IMAGE) && cosign sign --yes --key cosign.key --issue-certificate=true $IMAGE@$DIGEST
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    - run: crane manifest $(cosign triangulate $IMAGE) | jq .
    - name: verify
      run: DIGEST=$(crane digest $IMAGE) && cosign verify $IMAGE@$DIGEST
