name: keyed cosign @ttl.sh

on:
  push:
    branches: ['main']

env:
  IMAGE: ttl.sh/keyed-${{github.sha}}:1h

jobs:
  cosign-keyed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: sigstore/cosign-installer@main
      with:
        cosign-release: "v2.1.1"
    - run: cosign copy alpine $IMAGE
    - uses: imjasonh/setup-crane@v0.1
    - name: save digest
      run: echo "DIGEST=$(crane digest $IMAGE)" >> "$GITHUB_ENV"
    - name: check porcelain
      run: echo "PORCELAIN=$([ -z "`git status --porcelain`" ] && echo 0 || echo 1)" >> "$GITHUB_ENV"
    - name: sign
      run: cosign sign --yes --key cosign.key -a commit=${{github.sha}} -a ref_name=${{github.ref_name}} -a ref_protected=${{github.ref_protected}} -a porcelain=$PORCELAIN $IMAGE@$DIGEST
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    - run: crane manifest $(cosign triangulate $IMAGE) | jq .
    - name: verify
      run: cosign verify --key cosign.pub $IMAGE@$DIGEST
    - name: verify claims
      run: cosign verify --key cosign.pub -a ref_name=${{github.ref_name}} -a ref_protected=${{github.ref_protected}} -a porcelain=0 $IMAGE@$DIGEST
