# here we use public fulcio + chainguard TSA and we avoid using Rekor

# Notes
# 1. currently output of --offline=false (=online) reports that verification is performed offline
# this is a bug. verification is in fact performed online https://github.com/sigstore/cosign/issues/3423
# 2. here we verify tlog inclusion only for keyless, but it could be done for auditable approach as well
# 3. all jobs run in containers

name: sigstore keyless with TSA
on:
  push:
env:
  CERT_OIDC_ISSUER: https://token.actions.githubusercontent.com
  CERT_IDENTITY: ${{ github.server_url }}/${{ github.workflow_ref }}
  TARGET_IMAGE_URI: ttl.sh/falcorocks-${{ github.sha }}:1h
jobs:
  sign:
    runs-on: ubuntu
    container: alpine
    permissions:
      packages: write
      id-token: write
    steps:
      - run: apk add cosign
      - run: cosign copy -f alpine $TARGET_IMAGE_URI
      - run: cosign sign --yes $TARGET_IMAGE_URI --tlog-upload=false --timestamp-server-url=https://tsa.enforce.dev/api/v1/timestamp
  verify:
    runs-on: ubuntu
    container: alpine
    permissions:
      packages: write
      id-token: write
    steps:
      - run: apk add cosign curl
      - run: curl https://tsa.enforce.dev/api/v1/timestamp/certchain > ts_chain.pem
      - run: cosign verify $TARGET_IMAGE_URI --timestamp-certificate-chain=ts_chain.pem --insecure-ignore-tlog=true --certificate-identity=$CERT_IDENTITY --certificate-oidc-issuer=$CERT_OIDC_ISSUER